/**
 * Settings Configuration
 * Organizes all script settings into logical groups for the settings UI
 */

export const settingsGroups = {
    general: {
        title: '常规设置',
        icon: '⚙️',
        settings: {
            networkAlert: {
                id: 'networkAlert',
                label: '无法获取市场价格数据时显示警报',
                type: 'checkbox',
                default: true,
            },
            chatCommands: {
                id: 'chatCommands',
                label: '启用聊天命令 (/item, /wiki, /market)',
                type: 'checkbox',
                default: true,
                help: '在聊天框输入 /item、/wiki 或 /market 后接物品名称。例如：/item radiant fiber',
            },
            chat_mentionTracker: {
                id: 'chat_mentionTracker',
                label: '在聊天中被提及（@）时显示徽章',
                type: 'checkbox',
                default: true,
                help: '当有人在聊天中 @你时，在聊天标签页上显示红色数字徽章',
            },
            chat_popOut: {
                id: 'chat_popOut',
                label: '启用“弹出聊天窗口”按钮',
                type: 'checkbox',
                default: true,
                help: '在聊天面板添加一个按钮，用于在独立浏览器窗口中打开聊天，支持多频道分屏视图',
            },
            altClickNavigation: {
                id: 'altClickNavigation',
                label: 'Alt+点击物品跳转至制作/采集或百科',
                type: 'checkbox',
                default: true,
                help: '按住 Alt/Option 键并点击任何物品，可跳转至其制作/采集页面；若不可制作则跳转至物品百科',
            },
            collectionNavigation: {
                id: 'collectionNavigation',
                label: '为收藏品添加导航按钮',
                type: 'checkbox',
                default: true,
                help: '点击收藏品时添加“查看动作”和“物品百科”按钮',
            },
        },
    },

    actionPanel: {
        title: '动作面板增强',
        icon: '⚡',
        settings: {
            totalActionTime: {
                id: 'totalActionTime',
                label: '左上角：动作条显示模式',
                type: 'select',
                default: 'full',
                options: [
                    { value: 'full', label: '详细 (所有属性 + 时间)' },
                    { value: 'compact', label: '紧凑 (所有属性，限制宽度)' },
                    { value: 'minimal', label: '精简 (仅剩余次数 + 时间)' },
                ],
                help: '选择动作条显示的信息。详细模式显示所有统计；紧凑模式限制宽度以适配宽屏；精简模式仅显示剩余动作和完成时间。',
            },
            actionPanel_totalTime: {
                id: 'actionPanel_totalTime',
                label: '动作面板：总时间、到达目标等级所需次数、时薪经验',
                type: 'checkbox',
                default: true,
            },
            actionPanel_totalTime_quickInputs: {
                id: 'actionPanel_totalTime_quickInputs',
                label: '动作面板：快捷输入按钮 (小时、数量预设、最大值)',
                type: 'checkbox',
                default: true,
            },
            actionPanel_foragingTotal: {
                id: 'actionPanel_foragingTotal',
                label: '动作面板：多产出采集动作的总利润',
                type: 'checkbox',
                default: true,
            },
            actionQueue: {
                id: 'actionQueue',
                label: '动作队列：显示总时间和预计完成时刻',
                type: 'checkbox',
                default: true,
            },
            actionQueue_valueMode: {
                id: 'actionQueue_valueMode',
                label: '动作队列：价值计算模式',
                type: 'select',
                default: 'profit',
                options: [
                    { value: 'profit', label: '总利润 (营收 - 所有成本)' },
                    { value: 'estimated_value', label: '预估价值 (税后营收)' },
                ],
                help: '选择如何计算队列动作的总价值。利润显示扣除材料和药水后的净收益；预估价值显示扣除市场税后的毛收入（结果始终为正）。',
            },
            actionPanel_outputTotals: {
                id: 'actionPanel_outputTotals',
                label: '动作面板：在单次产出下方显示预期总产出',
                type: 'checkbox',
                default: true,
                help: '在动作输入框输入数量时，显示计算出的总产出数量',
            },
            actionPanel_maxProduceable: {
                id: 'actionPanel_maxProduceable',
                label: '动作面板：在制作动作上显示最大可制作数量',
                type: 'checkbox',
                default: true,
                help: '根据当前库存显示你可以制作多少个该物品',
            },
            actionPanel_showProfitPerHour: {
                id: 'actionPanel_showProfitPerHour',
                label: '动作面板：显示时薪利润 (Profit/hr)',
                type: 'checkbox',
                default: true,
                help: '在采集方块、生产和炼金面板中显示利润/小时统计',
            },
            actionPanel_showExpPerHour: {
                id: 'actionPanel_showExpPerHour',
                label: '动作面板：显示时薪经验 (Exp/hr)',
                type: 'checkbox',
                default: true,
                help: '在采集方块和动作面板各部分显示经验/小时统计',
            },
            actionPanel_hideNegativeProfit: {
                id: 'actionPanel_hideNegativeProfit',
                label: '动作面板：隐藏利润为负的动作',
                type: 'checkbox',
                default: false,
                help: '隐藏会导致亏损的动作面板',
            },
            requiredMaterials: {
                id: 'requiredMaterials',
                label: '动作面板：显示所需总材料和缺少材料',
                type: 'checkbox',
                default: true,
                help: '输入数量时，显示所需的材料总量以及当前缺少的差额',
            },
            alchemy_profitDisplay: {
                id: 'alchemy_profitDisplay',
                label: '炼金面板：显示利润计算器',
                type: 'checkbox',
                default: true,
                help: '基于成功率和市场价格，显示炼金动作的利润/小时和利润/天',
            },
            alchemy_transmuteHistory: {
                id: 'alchemy_transmuteHistory',
                label: '炼金面板：追踪并查看转化（Transmute）历史',
                type: 'checkbox',
                default: true,
                help: '记录转化阶段并在炼金面板的历史查看器标签页中显示',
            },
            alchemy_coinifyHistory: {
                id: 'alchemy_coinifyHistory',
                label: '炼金面板：追踪并查看金币化（Coinify）历史',
                type: 'checkbox',
                default: true,
                help: '记录金币化阶段并在炼金面板的历史查看器标签页中显示',
            },
            actions_missingMaterialsButton: {
                id: 'actions_missingMaterialsButton',
                label: '在生产面板显示“购买缺失材料”按钮',
                type: 'checkbox',
                default: true,
                help: '在面板添加按钮，点击可打开市场并自动切换到缺少材料的标签页',
            },
            actions_missingMaterialsButton_ignoreQueue: {
                id: 'actions_missingMaterialsButton_ignoreQueue',
                label: '计算缺失材料时忽略已排队的动作',
                type: 'checkbox',
                default: false,
                help: '启用后，缺失材料计算仅考虑当前动作，忽略队列中已预留的材料。默认（关闭）会统计队列需求。',
            },
            lootLogStats: {
                id: 'lootLogStats',
                label: '掉落日志统计',
                type: 'checkbox',
                default: true,
                help: '在掉落日志中显示总价值、平均耗时和每日预期产出',
            },
            inventoryCountDisplay: {
                id: 'inventoryCountDisplay',
                label: '动作面板：显示产出物品的当前库存数量',
                type: 'checkbox',
                default: true,
                help: '在动作方块和详情面板中显示你当前拥有的产出物品数量',
            },
            actions_pinnedPage: {
                id: 'actions_pinnedPage',
                label: '在导航栏添加“已固定动作”页面',
                type: 'checkbox',
                default: true,
                help: '在左侧导航栏添加一个“固定”按钮，集中显示所有已固定的动作及其技能、等级、利润和经验率',
            },
        },
    },

    tooltips: {
        title: '物品提示增强 (Tooltip)',
        icon: '💬',
        settings: {
            itemTooltip_prices: {
                id: 'itemTooltip_prices',
                label: '显示 24 小时平均市场价格',
                type: 'checkbox',
                default: true,
            },
            itemTooltip_profit: {
                id: 'itemTooltip_profit',
                label: '显示生产成本和利润',
                type: 'checkbox',
                default: true,
            },
            itemTooltip_detailedProfit: {
                id: 'itemTooltip_detailedProfit',
                label: '在利润显示中包含详细材料清单',
                type: 'checkbox',
                default: false,
                help: '显示包含买一价/卖一价、动作/小时和利润细分的材料成本表',
            },
            itemTooltip_multiActionProfit: {
                id: 'itemTooltip_multiActionProfit',
                label: '显示该物品所有相关动作的利润对比',
                type: 'checkbox',
                default: false,
                help: '高亮显示利润最高的动作，并在下方列出其他动作（制作、金币化、分解、转化）的摘要',
            },
            itemTooltip_expectedValue: {
                id: 'itemTooltip_expectedValue',
                label: '显示可开启容器的预期价值',
                type: 'checkbox',
                default: true,
            },
            expectedValue_showDrops: {
                id: 'expectedValue_showDrops',
                label: '预期价值掉落列表显示',
                type: 'select',
                default: 'All',
                options: [
                    { value: 'Top 5', label: '价值前 5' },
                    { value: 'Top 10', label: '价值前 10' },
                    { value: 'All', label: '所有掉落' },
                    { value: 'None', label: '仅显示摘要' },
                ],
            },
            expectedValue_respectPricingMode: {
                id: 'expectedValue_respectPricingMode',
                label: '预期价值计算遵循定价模式设置',
                type: 'checkbox',
                default: true,
            },
            showConsumTips: {
                id: 'showConsumTips',
                label: 'HP/MP 消耗品：恢复速度与性价比',
                type: 'checkbox',
                default: true,
            },
            dungeonTokenTooltips: {
                id: 'dungeonTokenTooltips',
                label: '副本代币：显示可兑换物品及成本',
                type: 'checkbox',
                default: true,
            },
            enhanceSim: {
                id: 'enhanceSim',
                label: '显示强化模拟器计算结果',
                type: 'checkbox',
                default: true,
            },
            enhanceSim_showConsumedItemsDetail: {
                id: 'enhanceSim_showConsumedItemsDetail',
                label: '强化提示：显示消耗物品的详细细分',
                type: 'checkbox',
                default: false,
                help: "启用后，在“贤者之镜”计算中显示每个消耗物品的基础成本/材料/保护项细分",
            },
            itemTooltip_gathering: {
                id: 'itemTooltip_gathering',
                label: '显示采集来源和利润',
                type: 'checkbox',
                default: true,
                help: '显示产出此物品的采集动作（采集、伐木、挤奶）',
            },
            itemTooltip_gatheringRareDrops: {
                id: 'itemTooltip_gatheringRareDrops',
                label: '显示采集时的稀有掉落',
                type: 'checkbox',
                default: true,
                help: '显示该采集区域可能产出的稀有掉落物（如小行星带的专业之线）',
            },
            itemTooltip_abilityStatus: {
                id: 'itemTooltip_abilityStatus',
                label: '显示技能书学习状态',
                type: 'checkbox',
                default: true,
                help: '在技能书提示中显示是否已学习以及当前等级/进度',
            },
            itemTooltip_enhancementMilestones: {
                id: 'itemTooltip_enhancementMilestones',
                label: '显示强化里程碑 (+5/+7/+10/+12)',
                type: 'checkbox',
                default: false,
                help: '在未强化的装备提示中显示达到 +5, +7, +10 和 +12 的预期成本和经验',
            },
        },
    },

    enhancementSimulator: {
        title: '强化模拟器设置',
        icon: '✨',
        settings: {
            enhanceSim_autoDetect: {
                id: 'enhanceSim_autoDetect',
                label: '自动检测个人属性 (关闭 = 使用市场默认值)',
                type: 'checkbox',
                default: false,
                help: '建议大多数玩家使用市场默认值，以查看专业强化师的现实成本',
            },
            enhanceSim_enhancingLevel: {
                id: 'enhanceSim_enhancingLevel',
                label: '强化技能等级',
                type: 'number',
                default: 140,
                min: 1,
                max: 150,
                help: '默认：140 (专业强化师等级)',
            },
            enhanceSim_houseLevel: {
                id: 'enhanceSim_houseLevel',
                label: '房屋天文台等级',
                type: 'number',
                default: 8,
                min: 0,
                max: 8,
                help: '默认：8 (最高等级)',
            },
            enhanceSim_toolBonus: {
                id: 'enhanceSim_toolBonus',
                label: '工具成功率加成 %',
                type: 'number',
                default: 6.05,
                min: 0,
                max: 30,
                step: 0.01,
                help: '默认：6.05 (星空强化器 +13)',
            },
            enhanceSim_speedBonus: {
                id: 'enhanceSim_speedBonus',
                label: '速度加成 %',
                type: 'number',
                default: 48.5,
                min: 0,
                max: 100,
                step: 0.1,
                help: "默认：48.5 (全套强化装 +10：衣服/裤子/手套 + 贤者项链)",
            },
            enhanceSim_blessedTea: {
                id: 'enhanceSim_blessedTea',
                label: '祝福茶 (Blessed Tea) 已激活',
                type: 'checkbox',
                default: true,
                help: '专业强化师使用此茶来减少尝试次数',
            },
            enhanceSim_ultraEnhancingTea: {
                id: 'enhanceSim_ultraEnhancingTea',
                label: '究极强化茶 (Ultra) 已激活',
                type: 'checkbox',
                default: true,
                help: '提供 +8 基础技能等级（随饮料浓度缩放）',
            },
            enhanceSim_superEnhancingTea: {
                id: 'enhanceSim_superEnhancingTea',
                label: '超级强化茶 (Super) 已激活',
                type: 'checkbox',
                default: false,
                help: '提供 +6 基础技能等级（极效更好）',
            },
            enhanceSim_enhancingTea: {
                id: 'enhanceSim_enhancingTea',
                label: '强化茶 已激活',
                type: 'checkbox',
                default: false,
                help: '提供 +3 基础技能等级（极效更好）',
            },
            enhanceSim_drinkConcentration: {
                id: 'enhanceSim_drinkConcentration',
                label: '饮料浓度 %',
                type: 'number',
                default: 12.9,
                min: 0,
                max: 20,
                step: 0.1,
                help: '默认：12.9 (暴饮 +10)',
            },
        },
    },

    enhancementTracker: {
        title: '强化追踪器',
        icon: '📊',
        settings: {
            enhancementTracker: {
                id: 'enhancementTracker',
                label: '启用强化追踪器',
                type: 'checkbox',
                default: false,
                help: '追踪强化的尝试次数、成本和统计数据',
            },
            enhancementTracker_showOnlyOnEnhancingScreen: {
                id: 'enhancementTracker_showOnlyOnEnhancingScreen',
                label: '仅在强化界面显示追踪器',
                type: 'checkbox',
                default: false,
                help: '不在强化界面时隐藏追踪器面板',
            },
        },
    },

    economy: {
        title: '经济与库存',
        icon: '💰',
        settings: {
            networth: {
                id: 'networth',
                label: '右上角：显示当前资产 (净资产)',
                type: 'checkbox',
                default: true,
                help: '强化物品按强化模拟器计算的价值估算',
            },
            invWorth: {
                id: 'invWorth',
                label: '库存下方：显示库存总览',
                type: 'checkbox',
                default: true,
            },
            invSort: {
                id: 'invSort',
                label: '按价值对库存物品排序',
                type: 'checkbox',
                default: true,
            },
            invSort_showBadges: {
                id: 'invSort_showBadges',
                label: '按买一/卖一价排序时显示价值徽章',
                type: 'checkbox',
                default: false,
            },
            invSort_badgesOnNone: {
                id: 'invSort_badgesOnNone',
                label: '未排序（None）时的徽章类型',
                type: 'select',
                default: 'None',
                options: [
                    { value: 'None', label: '不显示' },
                    { value: 'Ask', label: '卖一价 (Ask)' },
                    { value: 'Bid', label: '买一价 (Bid)' }
                ],
            },
            invSort_netOfTax: {
                id: 'invSort_netOfTax',
                label: '徽章价值扣除市场税',
                type: 'checkbox',
                default: false,
            },
            invSort_sortEquipment: {
                id: 'invSort_sortEquipment',
                label: '为装备分类启用排序',
                type: 'checkbox',
                default: false,
            },
            invBadgePrices: {
                id: 'invBadgePrices',
                label: '在物品图标上显示价格徽章',
                type: 'checkbox',
                default: false,
                help: '在库存物品上直接显示单个物品的卖一价和买一价',
            },
            invCategoryTotals: {
                id: 'invCategoryTotals',
                label: '在库存中显示各分类总价',
                type: 'checkbox',
                default: true,
                help: '显示每个库存分类下所有物品的总市场价值',
            },
            profitCalc_pricingMode: {
                id: 'profitCalc_pricingMode',
                label: '利润计算定价模式',
                type: 'select',
                default: 'hybrid',
                options: [
                    { value: 'conservative', label: '保守 (卖一/买一 - 快速交易)' },
                    { value: 'hybrid', label: '混合 (卖一/卖一 - 即买耐卖)' },
                    { value: 'optimistic', label: '乐观 (买一/卖一 - 耐心交易)' },
                ],
            },
            actions_artisanMaterialMode: {
                id: 'actions_artisanMaterialMode',
                label: '缺失材料：工匠茶（Artisan）需求模式',
                type: 'select',
                default: 'expected',
                options: [
                    { value: 'expected', label: '期望值 (平均消耗)' },
                    { value: 'worst-case', label: '最坏情况 (单次制作向上取整)' },
                ],
                help: '在建议购买时，如何计算工匠茶对材料减少的影响。',
            },
            networth_highEnhancementUseCost: {
                id: 'networth_highEnhancementUseCost',
                label: '高强化物品使用计算成本而非市场价',
                type: 'checkbox',
                default: true,
                help: '高强化物品（+13及以上）的市场价不可靠。建议使用计算出的强化成本。',
            },
            networth_highEnhancementMinLevel: {
                id: 'networth_highEnhancementMinLevel',
                label: '开始使用计算成本的最低强化等级',
                type: 'select',
                default: 13,
                options: [
                    { value: 10, label: '+10 及以上' },
                    { value: 11, label: '+11 及以上' },
                    { value: 12, label: '+12 及以上' },
                    { value: 13, label: '+13 及以上 (推荐)' },
                    { value: 15, label: '+15 及以上' },
                ],
                help: '停止信任市场价格并转用计算成本的强化等级阈值',
            },
            networth_includeCowbells: {
                id: 'networth_includeCowbells',
                label: '净资产包含牛铃 (Cowbells)',
                type: 'checkbox',
                default: false,
                help: '牛铃不可交易，但会根据 10联装牛铃的市场价计算其价值',
            },
            networth_includeTaskTokens: {
                id: 'networth_includeTaskTokens',
                label: '净资产包含任务代币',
                type: 'checkbox',
                default: true,
                help: '根据任务商店宝箱的预期价值估算代币价值。关闭则不计入净资产。',
            },
            networth_abilityBooksAsInventory: {
                id: 'networth_abilityBooksAsInventory',
                label: '将技能书计入流动资产 (库存价值)',
                type: 'checkbox',
                default: false,
                help: '将技能书从固定资产移至流动资产。如果你打算卖掉它们，请开启此项。',
            },
            networth_historyChart: {
                id: 'networth_historyChart',
                label: '启用净资产历史图表',
                type: 'checkbox',
                default: true,
                help: '记录每小时的净资产快照，并在总净资产旁显示图表图标。关闭将停止记录并隐藏按钮。',
            },
            autoAllButton: {
                id: 'autoAllButton',
                label: '开启战利品箱时自动点击“全部”按钮',
                type: 'checkbox',
                default: true,
                help: '打开容器（箱子、板框、缓存）时自动点击全部开启',
            },
            autoAllButton_excludeSeals: {
                id: 'autoAllButton_excludeSeals',
                label: '自动点击：跳过“印记 (Seal of...)”类物品',
                type: 'checkbox',
                default: true,
                help: '开启后，迷宫产出的印记类物品不会被自动打开',
            },
        },
    },

    skills: {
        title: '技能',
        icon: '📚',
        settings: {
            xpTracker: {
                id: 'xpTracker',
                label: '左侧边栏：在技能条上显示 XP/hr 速率',
                type: 'checkbox',
                default: true,
                help: '在导航面板的每个技能条下方显示实时的时薪经验',
            },
            xpTracker_timeTillLevel: {
                id: 'xpTracker_timeTillLevel',
                label: '技能提示：显示升级所需时间',
                type: 'checkbox',
                default: true,
                help: '在技能悬浮提示中，根据当前 XP/hr 估算距离下一级还需多久',
            },
            skillRemainingXP: {
                id: 'skillRemainingXP',
                label: '左侧边栏：显示升级所需剩余 XP',
                type: 'checkbox',
                default: true,
                help: '在技能进度条下方显示到达下一级还差多少 XP',
            },
            skillRemainingXP_blackBorder: {
                id: 'skillRemainingXP_blackBorder',
                label: '剩余 XP：添加黑色文字边框',
                type: 'checkbox',
                default: true,
                help: '为 XP 文字添加黑色描边/阴影，使其在进度条背景上更清晰',
            },
            skillbook: {
                id: 'skillbook',
                label: '技能书：显示到达目标等级所需书量（在百科窗口）',
                type: 'checkbox',
                default: true,
            },
        },
    },

    combat: {
        title: '战斗功能',
        icon: '⚔️',
        settings: {
            combatScore: {
                id: 'combatScore',
                label: '个人资料面板：显示装备评分 (Gear Score)',
                type: 'checkbox',
                default: true,
            },
            abilitiesTriggers: {
                id: 'abilitiesTriggers',
                label: '个人资料面板：显示技能与触发器',
                type: 'checkbox',
                default: true,
                help: '在资料下方显示已装备的技能、消耗品及其战斗触发条件',
            },
            characterCard: {
                id: 'characterCard',
                label: '个人资料面板：显示“查看卡片”按钮',
                type: 'checkbox',
                default: true,
                help: '添加按钮以在外部查看器中打开角色卡片',
            },
            dungeonTracker: {
                id: 'dungeonTracker',
                label: '副本追踪器：实时进度追踪',
                type: 'checkbox',
                default: true,
                help: '通过组队消息追踪副本耗时（经服务器验证）',
            },
            dungeonTrackerUI: {
                id: 'dungeonTrackerUI',
                label: '显示副本追踪器 UI 面板',
                type: 'checkbox',
                default: true,
                help: '显示包含波数计数器、历史记录和统计数据的副本进度面板',
            },
            dungeonTrackerChatAnnotations: {
                id: 'dungeonTrackerChatAnnotations',
                label: '在组队频道显示运行耗时',
                type: 'checkbox',
                default: true,
                help: '在“钥匙计数”消息中添加带颜色的时间标注（绿色代表快，红色代表慢）',
            },
            labyrinthTracker: {
                id: 'labyrinthTracker',
                label: '迷宫最高等级追踪',
                type: 'checkbox',
                default: true,
                help: '追踪每种怪物击败过的最高推荐等级，并显示在自动化标签页中',
            },
            combatSummary: {
                id: 'combatSummary',
                label: '战斗摘要：归来时显示详细统计',
                type: 'checkbox',
                default: true,
                help: '从战斗返回时显示场次/小时、收入、经验率等详细数据',
            },
            combatStats: {
                id: 'combatStats',
                label: '战斗统计：在战斗面板中显示“统计”标签页',
                type: 'checkbox',
                default: true,
                help: '添加统计按钮，显示收入、利润、消耗品成本、经验和掉落详情',
            },
            combatStats_keyPricing: {
                id: 'combatStats_keyPricing',
                label: '战斗统计：定价模式',
                type: 'select',
                default: 'ask',
                options: [
                    { value: 'ask', label: '卖一价 (Ask)' },
                    { value: 'bid', label: '买一价 (Bid)' }
                ],
                help: '计算收入、钥匙成本和利润时使用卖一价（即买）还是买一价（耐买）。',
            },
            combatStatsChatMessage: {
                id: 'combatStatsChatMessage',
                label: '战斗统计：聊天消息格式',
                type: 'template',
                default: [
                    { type: 'text', value: '战斗统计: ' },
                    { type: 'variable', key: '{duration}', label: '时长' },
                    { type: 'text', value: ' 耗时 | ' },
                    { type: 'variable', key: '{encountersPerHour}', label: '场次/小时' },
                    { type: 'text', value: ' EPH | ' },
                    { type: 'variable', key: '{income}', label: '总收入' },
                    { type: 'text', value: ' 收入 | ' },
                    { type: 'variable', key: '{dailyIncome}', label: '日收入' },
                    { type: 'text', value: ' 收入/天 | ' },
                    { type: 'variable', key: '{dailyConsumableCosts}', label: '日消耗成本' },
                    { type: 'text', value: ' 消耗/天 | ' },
                    { type: 'variable', key: '{dailyProfit}', label: '日利润' },
                    { type: 'text', value: ' 利润/天 | ' },
                    { type: 'variable', key: '{exp}', label: '经验/小时' },
                    { type: 'text', value: ' 经验/h | ' },
                    { type: 'variable', key: '{deathCount}', label: '死亡次数' },
                    { type: 'text', value: ' 死亡' },
                ],
                help: 'Ctrl+点击统计面板中的玩家卡片时发送的消息格式。点击“编辑模板”自定义。',
                templateVariables: [
                    { key: '{duration}', label: '时长', description: '战斗阶段时长' },
                    { key: '{encountersPerHour}', label: '场次/小时', description: '每小时遇敌次数 (EPH)' },
                    { key: '{income}', label: '总收入', description: '战斗获得的总收入' },
                    { key: '{dailyIncome}', label: '日收入', description: '平均每日收入' },
                    {
                        key: '{dailyConsumableCosts}',
                        label: '日消耗成本',
                        description: '平均每日消耗品成本',
                    },
                    { key: '{dailyProfit}', label: '日利润', description: '平均每日利润' },
                    { key: '{exp}', label: '经验/小时', description: '每小时获得的经验' },
                    { key: '{deathCount}', label: '死亡次数', description: '总死亡次数' },
                ],
            },
        },
    },

    tasks: {
        title: '任务 (Tasks)',
        icon: '📋',
        settings: {
            taskProfitCalculator: {
                id: 'taskProfitCalculator',
                label: '显示采集/生产任务的总利润',
                type: 'checkbox',
                default: true,
            },
            taskEfficiencyRating: {
                id: 'taskEfficiencyRating',
                label: '显示任务效率评分 (代币或利润/小时)',
                type: 'checkbox',
                default: true,
                help: '基于预期完成时间，显示经过颜色分级的效率分数。',
            },
            taskEfficiencyRatingMode: {
                id: 'taskEfficiencyRatingMode',
                label: '效率算法',
                type: 'select',
                default: 'gold',
                options: [
                    { value: 'tokens', label: '每小时任务代币' },
                    { value: 'gold', label: '每小时任务利润' },
                ],
                help: '选择按代币产出还是按总利润进行评分。',
            },
            taskEfficiencyGradient: {
                id: 'taskEfficiencyGradient',
                label: '使用相对渐变色',
                type: 'checkbox',
                default: false,
                help: '根据当前可见的任务相对对比来为效率评分着色。',
            },
            taskRerollTracker: {
                id: 'taskRerollTracker',
                label: '追踪任务刷新 (Reroll) 成本',
                type: 'checkbox',
                default: true,
                help: '追踪每次刷新任务花费的金币/牛铃（实验性功能 - 可能会导致 UI 卡顿）',
            },
            taskMapIndex: {
                id: 'taskMapIndex',
                label: '在任务上显示战斗区域索引号',
                type: 'checkbox',
                default: true,
            },
            taskIcons: {
                id: 'taskIcons',
                label: '在任务卡片上显示图标',
                type: 'checkbox',
                default: true,
                help: '在任务卡片背景显示半透明的物品/怪物图标',
            },
            taskIconsDungeons: {
                id: 'taskIconsDungeons',
                label: '在战斗任务上显示副本图标',
                type: 'checkbox',
                default: false,
                help: '显示该怪物存在于哪些副本（需要开启任务图标显示）',
            },
            taskSorter_autoSort: {
                id: 'taskSorter_autoSort',
                label: '打开任务面板时自动排序',
                type: 'checkbox',
                default: false,
                help: '打开任务面板时，自动按技能类型对任务进行排序',
            },
            taskSorter_hideButton: {
                id: 'taskSorter_hideButton',
                label: '隐藏“排序任务”按钮',
                type: 'checkbox',
                default: false,
                help: '隐藏手动排序按钮，但保持自动排序功能生效',
            },
            taskSorter_sortMode: {
                id: 'taskSorter_sortMode',
                label: '任务排序模式',
                type: 'select',
                default: 'skill',
                options: [
                    { value: 'skill', label: '技能 / 区域' },
                    { value: 'time', label: '完成所需时间' },
                ],
                help: '点击排序时的顺序。“完成时间”会让最快完成的任务排在前面；战斗任务和已完成任务排在最后。',
            },
            taskInventoryHighlighter: {
                id: 'taskInventoryHighlighter',
                label: '启用任务库存高亮按钮',
                type: 'checkbox',
                default: true,
                help: '添加一个按钮，用于变暗那些当前非战斗任务不需要的库存物品',
            },
            taskStatistics: {
                id: 'taskStatistics',
                label: '在任务面板显示统计按钮',
                type: 'checkbox',
                default: true,
                help: '添加统计按钮，显示溢出时间、预期奖励和完成预估',
            },
            taskGoMerge: {
                id: 'taskGoMerge',
                label: '点击“前往 (Go)”时合并重复任务',
                type: 'checkbox',
                default: true,
                help: '点击任务的 Go 时，将所有相同动作的进行中任务所需数量合并为一个单次预填数量',
            },
        },
    },

    ui: {
        title: 'UI 增强',
        icon: '🎨',
        settings: {
            formatting_useKMBFormat: {
                id: 'formatting_useKMBFormat',
                label: '使用 K/M/B 数字格式 (例如 1.5M 代替 1,500,000)',
                type: 'checkbox',
                default: true,
                help: '应用于工具提示、动作面板、利润显示及整个 UI 中的所有数字格式',
            },
            ui_externalLinks: {
                id: 'ui_externalLinks',
                label: '左侧边栏：显示外部工具链接',
                type: 'checkbox',
                default: true,
                help: '添加指向 Combat Sim、Market Tracker、Enhancelator 和 Milkonomy 的快速链接',
            },
            expPercentage: {
                id: 'expPercentage',
                label: '左侧边栏：显示技能经验百分比',
                type: 'checkbox',
                default: true,
            },
            itemIconLevel: {
                id: 'itemIconLevel',
                label: '图标左下角：显示装备等级',
                type: 'checkbox',
                default: true,
            },
            loadoutEnhancementDisplay: {
                id: 'loadoutEnhancementDisplay',
                label: '配置（Loadout）面板：在装备图标上显示拥有的最高强化等级',
                type: 'checkbox',
                default: true,
            },
            loadout_sortEnabled: {
                id: 'loadout_sortEnabled',
                label: '配置面板：启用拖拽重排序',
                type: 'checkbox',
                default: true,
            },
            showsKeyInfoInIcon: {
                id: 'showsKeyInfoInIcon',
                label: '钥匙图标左下角：显示区域索引',
                type: 'checkbox',
                default: true,
            },
            mapIndex: {
                id: 'mapIndex',
                label: '战斗区域：显示区域索引号',
                type: 'checkbox',
                default: true,
            },
            alchemyItemDimming: {
                id: 'alchemyItemDimming',
                label: '炼金面板：变暗等级不足的物品',
                type: 'checkbox',
                default: true,
            },
            marketFilter: {
                id: 'marketFilter',
                label: '市场：按等级、职业、部位过滤',
                type: 'checkbox',
                default: true,
            },
            marketSort: {
                id: 'marketSort',
                label: '市场：按盈利率排序物品',
                type: 'checkbox',
                default: true,
                help: '添加按钮以按利润/小时排序市场物品。无利润数据（仅掉落）的物品排在最后。',
            },
            fillMarketOrderPrice: {
                id: 'fillMarketOrderPrice',
                label: '自动填充市场订单的最佳价格',
                type: 'checkbox',
                default: true,
            },
            market_autoFillSellStrategy: {
                id: 'market_autoFillSellStrategy',
                label: '自动填充出售价格策略',
                type: 'select',
                default: 'match',
                options: [
                    { value: 'match', label: '匹配当前最低售价' },
                    { value: 'undercut', label: '压价 1 (最低售价 - 1)' },
                ],
                help: '创建出售列表时，选择是匹配还是略低于当前的最低售价',
            },
            market_autoFillBuyStrategy: {
                id: 'market_autoFillBuyStrategy',
                label: '自动填充求购价格策略',
                type: 'select',
                default: 'outbid',
                options: [
                    { value: 'outbid', label: '加价 1 (最高求购价 + 1)' },
                    { value: 'match', label: '匹配最高求购价' },
                    { value: 'undercut', label: '压价 1 (最高求购价 - 1)' },
                ],
                help: '创建求购订单时，选择是加价竞争、匹配还是略低于当前最高价',
            },
            market_autoClickMax: {
                id: 'market_autoClickMax',
                label: '出售对话框自动点击“最大”按钮',
                type: 'checkbox',
                default: true,
                help: '打开出售列表对话框时，自动点击数量字段的 Max 按钮',
            },
            market_quickInputButtons: {
                id: 'market_quickInputButtons',
                label: '市场：订单对话框添加快捷输入按钮',
                type: 'checkbox',
                default: true,
                help: '在买/卖对话框添加 10、100、1000 等预设数量按钮',
            },
            market_visibleItemCount: {
                id: 'market_visibleItemCount',
                label: '市场：显示物品持有量',
                type: 'checkbox',
                default: true,
                help: '浏览市场时显示你拥有的每种物品数量',
            },
            market_visibleItemCountOpacity: {
                id: 'market_visibleItemCountOpacity',
                label: '市场：未持有物品的透明度',
                type: 'slider',
                default: 0.25,
                min: 0,
                max: 1,
                step: 0.05,
                help: '当你拥有的物品数量为零时，该物品方块显示的透明度',
            },
            market_visibleItemCountIncludeEquipped: {
                id: 'market_visibleItemCountIncludeEquipped',
                label: '市场：统计包含已装备物品',
                type: 'checkbox',
                default: true,
                help: '在显示的持有数量中包含当前穿戴的装备',
            },
            market_showListingPrices: {
                id: 'market_showListingPrices',
                label: '市场：在个人列表中显示价格',
                type: 'checkbox',
                default: true,
                help: '在“我的列表”表格中显示顶层订单价格和总价值',
            },
            market_tradeHistory: {
                id: 'market_tradeHistory',
                label: '市场：显示个人交易历史',
                type: 'checkbox',
                default: true,
                help: '在市场中显示你最近一次买入/卖出该物品的价格',
            },
            market_tradeHistoryComparisonMode: {
                id: 'market_tradeHistoryComparisonMode',
                label: '市场：交易历史对比模式',
                type: 'select',
                default: 'instant',
                options: [
                    { value: 'instant', label: '即时 (Instant)' },
                    { value: 'listing', label: '挂单 (Orders)' },
                ],
                help: '即时模式：对比即时买/卖价。挂单模式：对比买/卖订单价。',
            },
            market_listingPricePrecision: {
                id: 'market_listingPricePrecision',
                label: '市场：挂单价格小数点精度',
                type: 'number',
                default: 2,
                min: 0,
                max: 4,
                help: '列表价格显示的位数',
            },
            market_showListingAge: {
                id: 'market_showListingAge',
                label: '市场：在“我的列表”中显示上架时长',
                type: 'checkbox',
                default: false,
                help: '显示每个列表创建了多久（例如 "3h 45m"）',
            },
            market_showTopOrderAge: {
                id: 'market_showTopOrderAge',
                label: '市场：显示竞争对手顶层订单的时长',
                type: 'checkbox',
                default: false,
                help: '显示每个列表中最领先的竞争订单的估计上架时长（需要开启估计时长功能）',
            },
            market_showEstimatedListingAge: {
                id: 'market_showEstimatedListingAge',
                label: '市场：在订单簿显示预估时长',
                type: 'checkbox',
                default: true,
                help: '利用列表 ID 插值估算所有市场列表的创建时间',
            },
            market_listingAgeFormat: {
                id: 'market_listingAgeFormat',
                label: '市场：时长显示格式',
                type: 'select',
                default: 'datetime',
                options: [
                    { value: 'elapsed', label: '流逝时间 (如 "3h 45m")' },
                    { value: 'datetime', label: '日期/时间 (如 "01-13 14:30")' },
                ],
                help: '选择如何显示列表的创建时间',
            },
            market_listingTimeFormat: {
                id: 'market_listingTimeFormat',
                label: '市场：日期时间格式中的小时制',
                type: 'select',
                default: '24hour',
                options: [
                    { value: '24hour', label: '24 小时制 (14:30)' },
                    { value: '12hour', label: '12 小时制 (2:30 PM)' },
                ],
                help: '使用日期/时间格式时的显示方式',
            },
            market_listingDateFormat: {
                id: 'market_listingDateFormat',
                label: '市场：日期格式顺序',
                type: 'select',
                default: 'MM-DD',
                options: [
                    { value: 'MM-DD', label: '月-日 (01-13)' },
                    { value: 'DD-MM', label: '日-月 (13-01)' },
                ],
                help: '使用日期/时间格式时的显示方式',
            },
            market_showOrderTotals: {
                id: 'market_showOrderTotals',
                label: '市场：在顶部显示总订单金额',
                type: 'checkbox',
                default: true,
                help: '在金币下方显示求购总额 (BO)、出售总额 (SO) 和待领取的金币 (💰)',
            },
            market_showHistoryViewer: {
                id: 'market_showHistoryViewer',
                label: '市场：在设置中显示历史查看器按钮',
                type: 'checkbox',
                default: true,
                help: '在设置面板添加“查看市场历史”按钮，用于查看和导出所有市场挂单历史',
            },
            market_showPhiloCalculator: {
                id: 'market_showPhiloCalculator',
                label: '市场：在设置中显示 Philo 赌狗计算器按钮',
                type: 'checkbox',
                default: true,
                help: '添加“Philo Gamba”按钮，计算将物品转化成贤者之石的投资回报率 (ROI)',
            },
            market_showQueueLength: {
                id: 'market_showQueueLength',
                label: '市场：显示队列长度预估',
                type: 'checkbox',
                default: true,
                help: '在买/卖按钮下方显示最佳价格的总量。预估值（同价格超过 20 个订单时）会以不同颜色显示。',
            },
            itemDictionary_transmuteRates: {
                id: 'itemDictionary_transmuteRates',
                label: '物品百科：显示转化成功率',
                type: 'checkbox',
                default: true,
                help: '在“转化自（炼金）”部分显示成功百分比',
            },
            itemDictionary_transmuteIncludeBaseRate: {
                id: 'itemDictionary_transmuteIncludeBaseRate',
                label: '物品百科：转化率包含基础成功率',
                type: 'checkbox',
                default: true,
                help: '启用后，显示总概率（基础率 × 掉落率）。关闭后，显示条件概率（仅掉落率，与“转化产出”部分一致）',
            },
        },
    },

    guild: {
        title: '公会',
        icon: '👥',
        settings: {
            guildXPTracker: {
                id: 'guildXPTracker',
                label: '追踪公会及成员随时间变化的经验',
                type: 'checkbox',
                default: true,
                help: '通过 WebSocket 消息记录公会和成员 XP 数据，用于计算 XP/hr',
            },
            guildXPDisplay: {
                id: 'guildXPDisplay',
                label: '在公会面板和排行榜显示 XP/hr 统计',
                type: 'checkbox',
                default: true,
                help: '在公会概览、成员和公会排行榜标签页显示经验率、排名和每周图表。使用此项时请禁用独立的 Guild XP/h 脚本。',
            },
        },
    },

    house: {
        title: '房屋 (House)',
        icon: '🏠',
        settings: {
            houseUpgradeCosts: {
                id: 'houseUpgradeCosts',
                label: '显示升级成本（包含市场价和库存对比）',
                type: 'checkbox',
                default: true,
            },
        },
    },

    notifications: {
        title: '通知',
        icon: '🔔',
        settings: {
            notifiEmptyAction: {
                id: 'notifiEmptyAction',
                label: '动作队列为空时发送浏览器通知',
                type: 'checkbox',
                default: false,
                help: '仅在游戏页面保持开启状态时有效',
            },
        },
    },

    colors: {
        title: '颜色自定义',
        icon: '🎨',
        settings: {
            color_profit: {
                id: 'color_profit',
                label: '利润/正值',
                type: 'color',
                default: '#047857',
                help: '用于利润、收益和正值的颜色',
            },
            color_loss: {
                id: 'color_loss',
                label: '亏损/负值',
                type: 'color',
                default: '#f87171',
                help: '用于亏损、成本和负值的颜色',
            },
            color_warning: {
                id: 'color_warning',
                label: '警告',
                type: 'color',
                default: '#ffa500',
                help: '用于警告和重要通知的颜色',
            },
            color_info: {
                id: 'color_info',
                label: '信息',
                type: 'color',
                default: '#60a5fa',
                help: '用于信息文本和高亮的颜色',
            },
            color_essence: {
                id: 'color_essence',
                label: '精华 (Essences)',
                type: 'color',
                default: '#c084fc',
                help: '用于精华掉落和精华相关文本的颜色',
            },
            color_tooltip_profit: {
                id: 'color_tooltip_profit',
                label: '提示框利润/正值',
                type: 'color',
                default: '#047857',
                help: '提示框中利润/正值的颜色（适用于浅色背景）',
            },
            color_tooltip_loss: {
                id: 'color_tooltip_loss',
                label: '提示框亏损/负值',
                type: 'color',
                default: '#dc2626',
                help: '提示框中亏损/负值的颜色（适用于浅色背景）',
            },
            color_tooltip_info: {
                id: 'color_tooltip_info',
                label: '提示框信息',
                type: 'color',
                default: '#2563eb',
                help: '提示框中信息文本的颜色（适用于浅色背景）',
            },
            color_tooltip_warning: {
                id: 'color_tooltip_warning',
                label: '提示框警告',
                type: 'color',
                default: '#ea580c',
                help: '提示框中警告文本的颜色（适用于浅色背景）',
            },
            color_text_primary: {
                id: 'color_text_primary',
                label: '主要文字',
                type: 'color',
                default: '#ffffff',
                help: '主要文字颜色',
            },
            color_text_secondary: {
                id: 'color_text_secondary',
                label: '次要文字',
                type: 'color',
                default: '#888888',
                help: '暗淡/次要文字颜色',
            },
            color_border: {
                id: 'color_border',
                label: '边框',
                type: 'color',
                default: '#444444',
                help: '边框和分隔符颜色',
            },
            color_gold: {
                id: 'color_gold',
                label: '金币/货币',
                type: 'color',
                default: '#ffa500',
                help: '用于金币和货币显示的颜色',
            },
            color_accent: {
                id: 'color_accent',
                label: '脚本强调色',
                type: 'color',
                default: '#22c55e',
                help: '脚本 UI 元素（按钮、标题、区域号、经验百分比等）的主要强调色',
            },
            color_remaining_xp: {
                id: 'color_remaining_xp',
                label: '剩余经验文字',
                type: 'color',
                default: '#FFFFFF',
                help: '左侧导航技能栏下方剩余 XP 的颜色',
            },
            color_xp_rate: {
                id: 'color_xp_rate',
                label: '经验速率文字',
                type: 'color',
                default: '#ffffff',
            },
            color_inv_count: {
                id: 'color_inv_count',
                label: '库存计数文字',
                type: 'color',
                default: '#ffffff',
                help: '动作方块和详情面板中显示的库存数量颜色',
            },
            color_invBadge_ask: {
                id: 'color_invBadge_ask',
                label: '库存徽章：卖一价',
                type: 'color',
                default: '#047857',
                help: '库存物品卖一价徽章颜色（卖家要价 - 代表更优的销售价值）',
            },
            color_invBadge_bid: {
                id: 'color_invBadge_bid',
                label: '库存徽章：买一价',
                type: 'color',
                default: '#60a5fa',
                help: '库存物品买一价徽章颜色（买家出价 - 代表即时卖出的价值）',
            },
            color_transmute: {
                id: 'color_transmute',
                label: '转化率',
                type: 'color',
                default: '#ffffff',
                help: '物品百科中转化成功百分比的颜色',
            },
            color_queueLength_known: {
                id: 'color_queueLength_known',
                label: '队列长度：已知值',
                type: 'color',
                default: '#ffffff',
                help: '确切队列长度的颜色（当所有可见订单已被统计时）',
            },
            color_queueLength_estimated: {
                id: 'color_queueLength_estimated',
                label: '队列长度：预估值',
                type: 'color',
                default: '#60a5fa',
                help: '预估队列长度的颜色（当同价订单超过 20 个进行推算时）',
            },
        },
    },
};

/**
 * Get all setting IDs in order
 * @returns {string[]} Array of setting IDs
 */
export function getAllSettingIds() {
    const ids = [];
    for (const group of Object.values(settingsGroups)) {
        for (const settingId of Object.keys(group.settings)) {
            ids.push(settingId);
        }
    }
    return ids;
}

/**
 * Get a setting definition by ID
 * @param {string} settingId - Setting ID
 * @returns {Object|null} Setting definition or null
 */
export function getSettingDefinition(settingId) {
    for (const group of Object.values(settingsGroups)) {
        if (group.settings[settingId]) {
            return group.settings[settingId];
        }
    }
    return null;
}

/**
 * Check if a setting has dependencies
 * @param {string} settingId - Setting ID
 * @returns {string[]} Array of dependency setting IDs
 */
export function getSettingDependencies(settingId) {
    const def = getSettingDefinition(settingId);
    return def?.dependencies || [];
}
